#!/bin/sh
echo "Bump! I'm your first-boot script."
clashdir=/etc/openclash
mv "$clashdir"/Country.mmdb "$clashdir"/Country.mmdb.bak
mv "$clashdir"/CountryLatest.mmdb "$clashdir"/Country.mmdb
# Delete me
rm /etc/init.d/firstrun